"""Public repository API used by DIMER Mitra Regressor tutorials.

The notebook surface imports from this package instead of reimplementing core model,
validation, inference, and artifact-boundary logic inline; the standalone notebooks carry
`tutorial_api.py` verbatim.
"""

from .tutorial_api import (
    ARTIFACT_FORMAT,
    ARTIFACT_FORMAT_VERSION,
    CONFIG_FILE,
    CONFIG_SHA256,
    DEFAULT_WEIGHTS_DIR,
    INPUT_SCHEMA,
    MANIFEST_NAME,
    MAX_FEATURES,
    MAX_TRAIN_ROWS,
    METRIC_IDS,
    MIN_TRAIN_ROWS,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    PINNED_REVISION,
    WEIGHTS_FILE,
    WEIGHTS_SHA256,
    MitraRegressionPipeline,
    cap_training_rows,
    evaluation_report,
    fit_mitra_predictor,
    normalize_autogluon_regression_metrics,
    predict_regression,
    read_csv_bytes,
    regression_metrics,
    safe_extract_archive,
    sha256_file,
    split_overlap_report,
    stage_missing_files,
    stage_verified_hf_snapshot,
    training_mean_baseline,
    validate_artifact_directory,
    validate_dimer_model_package,
    validate_inference_frame,
    validate_inputs,
    validate_labeled_frame,
    verify_snapshot,
    write_artifact_manifest,
)

__all__ = [
    "ARTIFACT_FORMAT",
    "ARTIFACT_FORMAT_VERSION",
    "CONFIG_FILE",
    "CONFIG_SHA256",
    "DEFAULT_WEIGHTS_DIR",
    "INPUT_SCHEMA",
    "MANIFEST_NAME",
    "MAX_FEATURES",
    "MAX_TRAIN_ROWS",
    "METRIC_IDS",
    "MIN_TRAIN_ROWS",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "MitraRegressionPipeline",
    "PINNED_REVISION",
    "WEIGHTS_FILE",
    "WEIGHTS_SHA256",
    "cap_training_rows",
    "evaluation_report",
    "fit_mitra_predictor",
    "normalize_autogluon_regression_metrics",
    "predict_regression",
    "read_csv_bytes",
    "regression_metrics",
    "safe_extract_archive",
    "sha256_file",
    "split_overlap_report",
    "stage_missing_files",
    "stage_verified_hf_snapshot",
    "training_mean_baseline",
    "validate_artifact_directory",
    "validate_dimer_model_package",
    "validate_inference_frame",
    "validate_inputs",
    "validate_labeled_frame",
    "verify_snapshot",
    "write_artifact_manifest",
]
