"""Public repository API used by DIMER Mitra Regressor tutorials.

The notebook surface imports from this package instead of reimplementing core model,
validation, inference, and artifact-boundary logic inline.
"""

from .tutorial_api import (
    ARTIFACT_FORMAT,
    ARTIFACT_FORMAT_VERSION,
    CONFIG_SHA256,
    MAX_FEATURES,
    MAX_TRAIN_ROWS,
    MIN_TRAIN_ROWS,
    MODEL_ID,
    PINNED_REVISION,
    WEIGHTS_SHA256,
    cap_training_rows,
    fit_mitra_predictor,
    normalize_autogluon_regression_metrics,
    predict_regression,
    read_csv_bytes,
    regression_metrics,
    safe_extract_archive,
    sha256_file,
    split_overlap_report,
    stage_verified_hf_snapshot,
    validate_artifact_directory,
    validate_dimer_model_package,
    validate_inference_frame,
    validate_labeled_frame,
    write_artifact_manifest,
)

__all__ = [
    "ARTIFACT_FORMAT",
    "ARTIFACT_FORMAT_VERSION",
    "CONFIG_SHA256",
    "MAX_FEATURES",
    "MAX_TRAIN_ROWS",
    "MIN_TRAIN_ROWS",
    "MODEL_ID",
    "PINNED_REVISION",
    "WEIGHTS_SHA256",
    "cap_training_rows",
    "fit_mitra_predictor",
    "normalize_autogluon_regression_metrics",
    "predict_regression",
    "read_csv_bytes",
    "regression_metrics",
    "safe_extract_archive",
    "sha256_file",
    "split_overlap_report",
    "stage_verified_hf_snapshot",
    "validate_artifact_directory",
    "validate_dimer_model_package",
    "validate_inference_frame",
    "validate_labeled_frame",
    "write_artifact_manifest",
]
